# Generated by Django 5.1.6 on 2025-03-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='songlyrics',
            constraint=models.UniqueConstraint(fields=('song', 'line_number'), name='unique_line_per_song'),
        ),
    ]
