# Generated by Django 5.1.6 on 2025-03-09 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_songlyrics_unique_line_per_song'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='songlyrics',
            name='unique_line_per_song',
        ),
    ]
