# Generated by Django 5.1.6 on 2025-03-31 19:15

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_songlyrics_unique_line_per_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='search_text',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
