# Generated by Django 5.1.6 on 2025-04-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_song_title_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
