# Generated by Django 5.1.6 on 2025-04-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_song_lyrics_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='search_text',
        ),
    ]
