# Generated by Django 5.1.6 on 2025-04-08 14:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_song_search_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
    ]
