# Generated by Django 5.1.6 on 2025-04-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_song_words'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='lyrics_text',
            new_name='search_text',
        ),
    ]
