# Generated by Django 5.1.6 on 2025-08-24 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='songlyrics',
            unique_together={('song', 'line_number')},
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='api.song')),
            ],
        ),
        migrations.AddField(
            model_name='songlyrics',
            name='annotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='api.annotation'),
        ),
    ]
